"""initial schema: fighters, events, fights, rounds, elo_snapshots, computed_features

Revision ID: 96ab1f67fb42
Revises:
Create Date: 2026-04-14 13:28:10.472405

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '96ab1f67fb42'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_table('fighters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('nickname', sa.String(length=200), nullable=True),
    sa.Column('height_inches', sa.Float(), nullable=True),
    sa.Column('reach_inches', sa.Float(), nullable=True),
    sa.Column('leg_reach_inches', sa.Float(), nullable=True),
    sa.Column('stance', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fighters'))
    )
    op.create_table('fighter_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], name=op.f('fk_fighter_aliases_fighter_id_fighters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fighter_aliases')),
    sa.UniqueConstraint('alias_name', 'source', name='uq_fighter_aliases_name_source')
    )
    op.create_table('fights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('fighter_a_id', sa.Integer(), nullable=False),
    sa.Column('fighter_b_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('weight_class', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('method_detail', sa.String(length=100), nullable=True),
    sa.Column('round_finished', sa.Integer(), nullable=True),
    sa.Column('time_finished', sa.String(length=10), nullable=True),
    sa.Column('is_title_fight', sa.Boolean(), nullable=False),
    sa.Column('num_rounds', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('fighter_a_id != fighter_b_id', name=op.f('ck_fights_different_fighters')),
    sa.CheckConstraint('num_rounds IN (3, 5)', name=op.f('ck_fights_valid_num_rounds')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_fights_event_id_events')),
    sa.ForeignKeyConstraint(['fighter_a_id'], ['fighters.id'], name=op.f('fk_fights_fighter_a_id_fighters')),
    sa.ForeignKeyConstraint(['fighter_b_id'], ['fighters.id'], name=op.f('fk_fights_fighter_b_id_fighters')),
    sa.ForeignKeyConstraint(['winner_id'], ['fighters.id'], name=op.f('fk_fights_winner_id_fighters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fights'))
    )
    op.create_table('computed_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('feature_set_version', sa.String(length=50), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fight_id'], ['fights.id'], name=op.f('fk_computed_features_fight_id_fights')),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], name=op.f('fk_computed_features_fighter_id_fighters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_computed_features'))
    )
    op.create_table('elo_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=50), nullable=False),
    sa.Column('elo_type', sa.String(length=20), nullable=False),
    sa.Column('elo_before', sa.Float(), nullable=False),
    sa.Column('elo_after', sa.Float(), nullable=False),
    sa.Column('k_factor_used', sa.Float(), nullable=False),
    sa.Column('fight_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fight_id'], ['fights.id'], name=op.f('fk_elo_snapshots_fight_id_fights')),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], name=op.f('fk_elo_snapshots_fighter_id_fighters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_elo_snapshots'))
    )
    op.create_table('round_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('sig_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('sig_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('head_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('body_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('leg_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('distance_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('clinch_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('ground_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('takedowns_landed', sa.Integer(), nullable=True),
    sa.Column('takedowns_attempted', sa.Integer(), nullable=True),
    sa.Column('submission_attempts', sa.Integer(), nullable=True),
    sa.Column('reversals', sa.Integer(), nullable=True),
    sa.Column('control_time_seconds', sa.Integer(), nullable=True),
    sa.Column('knockdowns', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('round_number BETWEEN 1 AND 5', name=op.f('ck_round_stats_valid_round_number')),
    sa.ForeignKeyConstraint(['fight_id'], ['fights.id'], name=op.f('fk_round_stats_fight_id_fights')),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], name=op.f('fk_round_stats_fighter_id_fighters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_round_stats'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('round_stats')
    op.drop_table('elo_snapshots')
    op.drop_table('computed_features')
    op.drop_table('fights')
    op.drop_table('fighter_aliases')
    op.drop_table('fighters')
    op.drop_table('events')
    # ### end Alembic commands ###
