"""add sherdog_url and pre_ufc_record to fighters

Revision ID: b394e0f2770e
Revises: 30a14a290754
Create Date: 2026-04-19 00:37:38.715251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b394e0f2770e'
down_revision: Union[str, Sequence[str], None] = '30a14a290754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fighters', sa.Column('sherdog_url', sa.String(length=500), nullable=True))
    op.add_column('fighters', sa.Column('pre_ufc_record', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fighters', 'pre_ufc_record')
    op.drop_column('fighters', 'sherdog_url')
    # ### end Alembic commands ###
