"""add elo_after_shrinkage to elo_snapshots

Revision ID: c1d121894bba
Revises: d22d037d5b00
Create Date: 2026-04-15 00:16:53.167350

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1d121894bba"
down_revision: Union[str, Sequence[str], None] = "d22d037d5b00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first, backfill from elo_after, then enforce NOT NULL.
    # This avoids constraint violations if elo_snapshots already has rows.
    op.add_column("elo_snapshots", sa.Column("elo_after_shrinkage", sa.Float(), nullable=True))
    op.execute("UPDATE elo_snapshots SET elo_after_shrinkage = elo_after")
    op.alter_column("elo_snapshots", "elo_after_shrinkage", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("elo_snapshots", "elo_after_shrinkage")
    # ### end Alembic commands ###
