/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Liveness probe — no DB touch, returns app version.
         */
        get: operations["liveness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness probe — 200 if SELECT 1 succeeds within 1s, else 503.
         */
        get: operations["readiness_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fighters/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fighter
         * @description Get fighter ratings by name.
         *
         *     Returns full rating details for a single match, or a candidate list
         *     when multiple fighters match the search term (D-03, D-13).
         */
        get: operations["get_fighter_api_v1_fighters__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rankings/{division}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rankings
         * @description Get top fighters in a division ranked by Elo.
         *
         *     The division parameter supports partial matching (e.g., 'light' matches
         *     'Lightweight'). The top parameter caps at 100 (T-09-02).
         */
        get: operations["get_rankings_api_v1_rankings__division__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matchup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Matchup
         * @description Compare two fighters across all matchup dimensions.
         *
         *     Returns physical differentials, Elo comparison, striking/grappling
         *     matrices, and style analysis.
         */
        get: operations["get_matchup_api_v1_matchup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fighters/{name}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fighter History
         * @description Get a fighter's chronological Elo trajectory.
         *
         *     Optionally filter by division and elo_type (overall, striking, grappling).
         */
        get: operations["get_fighter_history_api_v1_fighters__name__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict
         * @description Predict fight outcome for fighter_a vs fighter_b.
         *
         *     Forward-compatible with future META-V22-active responses (Phase 25 D-02).
         */
        post: operations["predict_api_v1_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DivisionRating
         * @description Rating detail for one division a fighter competes in.
         */
        DivisionRating: {
            /** Division */
            division: string;
            /** Elo */
            elo?: number | null;
            /** Striking Elo */
            striking_elo?: number | null;
            /** Grappling Elo */
            grappling_elo?: number | null;
            /**
             * Wins
             * @default 0
             */
            wins: number;
            /**
             * Losses
             * @default 0
             */
            losses: number;
            /**
             * Total Fights
             * @default 0
             */
            total_fights: number;
            /** Last Fight Date */
            last_fight_date?: string | null;
        };
        /**
         * EloHistoryPoint
         * @description A single point in a fighter's Elo trajectory.
         */
        EloHistoryPoint: {
            /**
             * Fight Date
             * Format: date
             */
            fight_date: string;
            /** Division */
            division: string;
            /** Elo Before */
            elo_before: number;
            /** Elo After */
            elo_after: number;
            /** Elo After Shrinkage */
            elo_after_shrinkage: number;
        };
        /**
         * EloHistoryResponse
         * @description Chronological Elo history for a fighter.
         */
        EloHistoryResponse: {
            /** Name */
            name: string;
            /** Fighter Id */
            fighter_id: number;
            /** History */
            history: components["schemas"]["EloHistoryPoint"][];
        };
        /**
         * FighterRatingResponse
         * @description Full fighter rating details (single match).
         */
        FighterRatingResponse: {
            /** Name */
            name: string;
            /** Id */
            id: number;
            /** Divisions */
            divisions: components["schemas"]["DivisionRating"][];
        };
        /**
         * FighterSearchResponse
         * @description Returned when a name search matches multiple fighters (D-13).
         */
        FighterSearchResponse: {
            /** Count */
            count: number;
            /** Results */
            results: components["schemas"]["FighterSearchResult"][];
        };
        /**
         * FighterSearchResult
         * @description Single fighter candidate returned when multiple matches exist.
         */
        FighterSearchResult: {
            /** Name */
            name: string;
            /** Id */
            id: number;
            /** Division */
            division?: string | null;
            /** Elo */
            elo?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PredictMatchupRequestV1
         * @description Request body for POST /api/v1/predict.
         */
        PredictMatchupRequestV1: {
            /**
             * Fighter A
             * @description Fighter A name (resolved via search_fighters).
             */
            fighter_a: string;
            /**
             * Fighter B
             * @description Fighter B name.
             */
            fighter_b: string;
            /**
             * Event Date
             * @description As-of date for the prediction. Defaults to today() if omitted.
             */
            event_date?: string | null;
            /**
             * Accept Schema Version
             * @description Response schema_version to emit. Default 1.2.0; partners on older contracts pass '1.0.0' or '1.1.0' to opt out of new fields. v1.3.0 is identical to v1.2.0 on the success path (byte-identical via forward-compat lock); v1.3.0 partners additionally opt in to the RFC 7807 application/problem+json error wrapper by sending `Accept: application/problem+json` on the request. See Phase 52 API-V26-01 / API-V26-02.
             * @default 1.2.0
             * @enum {string}
             */
            accept_schema_version: "1.0.0" | "1.1.0" | "1.2.0" | "1.3.0";
        };
        /**
         * PredictionMetadataV12
         * @description CONTRACT-V24-02: additive v1.2.0 prediction_metadata block.
         *
         *     Six partner-facing observability fields. Forward-compat: defaults to
         *     None on PredictorOutputV1, so v1.0.0 + v1.1.0 partners see this field
         *     absent / null (Phase 25 forward-compat lock).
         */
        PredictionMetadataV12: {
            /**
             * Odds Source
             * @description Source of the BFO closing-odds feature at predict time: 'live' (just-fetched), 'cache' (DB-stashed), 'nan' (absent).
             * @enum {string}
             */
            odds_source: "live" | "cache" | "nan";
            /**
             * Odds Timestamp Iso
             * @description ISO-8601 timestamp of when the odds row was fetched/cached. None when odds_source == 'nan'.
             */
            odds_timestamp_iso?: string | null;
            /**
             * Fighter A N Ufc Fights
             * @description Count of fighter_a's UFC fights at predict time.
             */
            fighter_a_n_ufc_fights: number;
            /**
             * Fighter B N Ufc Fights
             * @description Count of fighter_b's UFC fights at predict time.
             */
            fighter_b_n_ufc_fights: number;
            /**
             * Is Debutant Either
             * @description True if either fighter has zero prior UFC fights.
             */
            is_debutant_either: boolean;
            /**
             * Calibration Slice Brier
             * @description Brier score of the calibration slice whose date-window contains event_date (from models/meta/meta_v2_meta.json). None when no slice metadata is available.
             */
            calibration_slice_brier?: number | null;
        };
        /**
         * PredictorOutputV1
         * @description Response body for POST /api/v1/predict.
         *
         *     Two production response shapes (both validate against this single schema —
         *     base_prob / meta_prob / meta_learner_version / meta_skipped_reason are
         *     Optional per Phase 25 D-05(P19) forward-compat — Pitfall #5 prevention):
         *
         *     1. **META-V22-active (default since Phase 26, 2026-05-17):** the
         *        meta-learner `models/meta/meta_v2.joblib` loads on startup; for any
         *        matchup where BFO closing odds yield a non-NaN `closing_prob_diff`
         *        feature, the meta is invoked and `win_probability == meta_prob`
         *        (calibrated logistic stack over xgb_v2 OOF + Elo + closing odds + style
         *        differentials). `meta_skipped=False`, `meta_skipped_reason=None`,
         *        `meta_learner_version="v2"`.
         *
         *     2. **xgb_v2 base fallback:** triggers in two cases — (a) `closing_prob_diff`
         *        is NaN at predict time (no BFO closing odds for the matchup; typical
         *        for early-week or novel matchups before lines firm up), in which case
         *        `meta_skipped_reason="nan_closing_prob_diff"`; (b) the meta artifact is
         *        absent from disk, in which case `meta_skipped_reason="no_meta_artifact"`
         *        (a deployment misconfiguration; should not occur in production). In
         *        both cases `win_probability == base_prob == xgb_v2.predict_proba(...)`.
         *
         *     The same PredictorOutputV1 type covers both. Clients reading
         *     `meta_skipped_reason` can detect which path served their request.
         */
        PredictorOutputV1: {
            /**
             * Schema Version
             * @description Envelope minor version (per D-03; URL is major).
             * @default 1.0.0
             */
            schema_version: string;
            /**
             * Win Probability
             * @description Canonical user-facing probability fighter_a wins (D-05(P19)).
             */
            win_probability: number;
            /** Fighter A */
            fighter_a: string;
            /** Fighter B */
            fighter_b: string;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /**
             * Base Prob
             * @description Raw XGBoost probability before meta-learner wrapping.
             */
            base_prob?: number | null;
            /**
             * Meta Prob
             * @description Meta-learner output probability; None when meta is skipped.
             */
            meta_prob?: number | null;
            /**
             * Meta Learner Version
             * @description Meta-learner version (e.g., 'v22.1') when meta is active; None otherwise.
             */
            meta_learner_version?: string | null;
            /**
             * Meta Skipped Reason
             * @description Reason meta was skipped (e.g., 'no_meta_artifact'); None when meta is active.
             */
            meta_skipped_reason?: string | null;
            /**
             * Gate Contract Ref
             * @description Path/version of gate contract used at prediction time (e.g., '.planning/gate_contract_v2.3.json'). Phase 32 D-04 (PARTNER-V23-01).
             */
            gate_contract_ref?: string | null;
            /**
             * Model Candidates
             * @description Supported model candidates with byte-identity SHAs. Each entry: {name: str, sha256: str, phase: str}. Phase 32 D-04 (PARTNER-V23-01).
             */
            model_candidates?: {
                [key: string]: string;
            }[] | null;
            /**
             * Phase Chain Audit Sha
             * @description AUDIT-01 chain leaf SHA (xgb_v2.joblib byte-identity). Phase 32 D-04 (PARTNER-V23-01).
             */
            phase_chain_audit_sha?: string | null;
            /** @description v1.2.0 additive observability block. Populated when client passes accept_schema_version='1.2.0'; None for v1.0.0/v1.1.0. */
            prediction_metadata?: components["schemas"]["PredictionMetadataV12"] | null;
            /**
             * Disclaimer
             * @description Entertainment / no-warranty / no-financial-advice disclaimer (HYGIENE-V24-02). Always populated; partners may surface or ignore. Constant string equal to ufc_prediction.api.disclaimer.DISCLAIMER_200W.
             * @default UFC Fight Prediction is a fantasy-MMA decision-support tool intended to help fantasy players reason about matchups using historical performance data. For informational and entertainment purposes; not financial or wagering advice; statistical estimates may diverge from actual outcomes. The win-probability values, baseline comparisons, and calibration metrics surfaced by this API are machine-learning estimates trained on historical UFC fight data through May 2026. They are NOT predictions of future events, NOT guarantees of any particular outcome, and NOT a recommendation to place, modify, or refrain from any wager, fantasy pick, or other transaction. Model uncertainty is real and material: closing-odds-derived features can be missing or stale at predict time, sample sizes for debutants and short-tenured fighters are small, and the underlying corpus is incomplete in well-documented ways (significant-strike classification noise, referee scoring variance, late-injury substitutions, weight-cut anomalies, and judging idiosyncrasies). Partners integrating this API into a downstream product are solely responsible for assessing fitness for purpose, complying with local laws regarding fantasy contests, sports wagering, and games of skill, and clearly framing model outputs to their end users as statistical estimates rather than outcome predictions or guaranteed results. Nothing in this API constitutes regulated financial advice, tax guidance, sports-betting recommendations, legal counsel, or professional consultation of any kind, and use of the API does not establish any advisory or fiduciary relationship.
             */
            disclaimer: string;
        };
        /**
         * RankedFighter
         * @description A fighter entry within a division ranking.
         */
        RankedFighter: {
            /** Rank */
            rank: number;
            /** Name */
            name: string;
            /** Fighter Id */
            fighter_id: number;
            /** Elo */
            elo: number;
            /** Fights */
            fights: number;
            /**
             * Last Active
             * Format: date
             */
            last_active: string;
        };
        /**
         * RankingsResponse
         * @description Ranked list of fighters within a division.
         */
        RankingsResponse: {
            /** Division */
            division: string;
            /** Fighters */
            fighters: components["schemas"]["RankedFighter"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_fighter_api_v1_fighters__name__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FighterSearchResponse"] | components["schemas"]["FighterRatingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rankings_api_v1_rankings__division__get: {
        parameters: {
            query?: {
                top?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                division: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_matchup_api_v1_matchup_get: {
        parameters: {
            query: {
                /** @description Fighter A name */
                a: string;
                /** @description Fighter B name */
                b: string;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fighter_history_api_v1_fighters__name__history_get: {
        parameters: {
            query?: {
                division?: string | null;
                elo_type?: string;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FighterSearchResponse"] | components["schemas"]["EloHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_api_v1_predict_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictMatchupRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictorOutputV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
